# Parameters will be stored and updated here
# Rather than in the command line
LogisticRegressionCV:
  penalty: 'l2'
  tol: 0.001
  C: .9
  fit_intercept: True 
  random_state: 42
  solver: 'liblinear'